### ISSUE TITLE
create delete volunteer task route

### ISSUE THREAD

**Issue by ryanchansf** [hack4impact-calpoly/youthArts#161]
Currently, admins don't have the ability to delete an entry in the Volunteers Task table of an opportunity. We need to create a `DELETE` request called `/api/volunteer/task` to delete a task (row) from the table of entries. For example, under the "General Committee Member" opportunity, any row represents a task that can be deleted. Don't worry about the frontend implementation— just the route for this task!

**Comment by TechLateef** [comment]
hello i will like to do this but i need some infor concerning the task what entry of the task is unique
